[package]
name = "c-tasks"
version = "0.1.0"
edition = "2021"
license = "GPL-3"
resolver = "2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[dependencies]
iced = "0.13.1"
iced_aw = "0.11"